import { useState, useEffect, useCallback } from 'react';
import { View, Text, StyleSheet, ScrollView, TouchableOpacity, RefreshControl } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { router } from 'expo-router';
import { colors, fonts, radius } from '../theme/brand';
import { IconArrowLeft } from '../components/Icons';
import { api } from '../lib/api';

type Booking = {
  id: string;
  slotDate: string;
  status: 'confirmed' | 'attended' | 'not_attended' | 'cancelled';
  bookingRef: string;
  bookedAt: string;
  isAutoGenerated?: boolean;
  slot?: { startTime: string; endTime: string; date: string };
  sessionType?: { name: string; color: string; kind: string };
  gym?: { name: string; id: string };
};

const STATUS_CONFIG: Record<string, { label: string; color: string; emoji: string }> = {
  confirmed:    { label: 'Confirmed',    color: '#00D46A', emoji: '✅' },
  attended:     { label: 'Attended',     color: '#00D4FF', emoji: '🏋️' },
  not_attended: { label: 'Missed',       color: '#FF6B6B', emoji: '😔' },
  cancelled:    { label: 'Cancelled',    color: 'rgba(255,255,255,0.3)', emoji: '❌' },
};

const FILTERS = ['All', 'Upcoming', 'Attended', 'Missed'] as const;
type Filter = typeof FILTERS[number];

export default function MyBookings() {
  const [bookings, setBookings] = useState<Booking[]>([]);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);
  const [filter, setFilter] = useState<Filter>('All');

  const load = useCallback(async (refresh = false) => {
    if (refresh) setRefreshing(true); else setLoading(true);
    try {
      const data: any = await api.get('/sessions/my-bookings');
      setBookings(Array.isArray(data) ? data : data?.bookings || data?.data || []);
    } catch {
      setBookings([]);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => { load(); }, []);

  const filtered = bookings.filter((b) => {
    if (filter === 'All') return true;
    if (filter === 'Upcoming') return b.status === 'confirmed';
    if (filter === 'Attended') return b.status === 'attended';
    if (filter === 'Missed') return b.status === 'not_attended';
    return true;
  });

  const cancelBooking = async (bookingId: string) => {
    try {
      await api.post(`/sessions/cancel/${bookingId}`, {});
      await load();
    } catch (e: any) {
      const { Alert } = require('react-native');
      Alert.alert('Error', e?.message || 'Could not cancel booking');
    }
  };

  return (
    <SafeAreaView style={s.root}>
      {/* Header */}
      <View style={s.header}>
        <TouchableOpacity style={s.back} onPress={() => router.back()}>
          <IconArrowLeft size={18} color="#fff" />
        </TouchableOpacity>
        <Text style={s.headerTitle}>My Bookings</Text>
        <View style={{ width: 38 }} />
      </View>

      {/* Filters */}
      <View style={s.filterRow}>
        {FILTERS.map((f) => (
          <TouchableOpacity key={f} style={[s.filterBtn, filter === f && s.filterBtnActive]} onPress={() => setFilter(f)}>
            <Text style={[s.filterText, filter === f && s.filterTextActive]}>{f}</Text>
          </TouchableOpacity>
        ))}
      </View>

      <ScrollView
        showsVerticalScrollIndicator={false}
        contentContainerStyle={s.scroll}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={() => load(true)} tintColor={colors.accent} />}
      >
        {loading ? (
          <View style={s.empty}><Text style={s.emptyText}>Loading bookings…</Text></View>
        ) : filtered.length === 0 ? (
          <View style={s.empty}>
            <Text style={{ fontSize: 40, marginBottom: 12 }}>📅</Text>
            <Text style={s.emptyTitle}>No {filter !== 'All' ? filter.toLowerCase() + ' ' : ''}bookings</Text>
            <Text style={s.emptyText}>Browse gyms and book a session to get started.</Text>
            <TouchableOpacity style={s.exploreBtn} onPress={() => router.push('/(tabs)/explore' as any)}>
              <Text style={s.exploreBtnText}>Explore Gyms</Text>
            </TouchableOpacity>
          </View>
        ) : (
          filtered.map((b) => {
            const cfg = STATUS_CONFIG[b.status] || STATUS_CONFIG.confirmed;
            const gymName = b.gym?.name || 'Gym';
            const sessionName = b.sessionType?.name || 'Gym Workout';
            const sessionColor = b.sessionType?.color || colors.accent;
            const date = b.slotDate
              ? new Date(b.slotDate + 'T12:00:00Z').toLocaleDateString('en-IN', { weekday: 'short', day: 'numeric', month: 'short' })
              : '—';
            const time = b.slot ? `${b.slot.startTime} – ${b.slot.endTime}` : '—';
            const canCancel = b.status === 'confirmed' && b.slotDate >= new Date(Date.now() + 5.5 * 3600 * 1000).toISOString().split('T')[0];

            return (
              <View key={b.id} style={[s.card, { borderColor: `${sessionColor}22` }]}>
                {/* Top row: session type + status */}
                <View style={s.cardTop}>
                  <View style={[s.typeDot, { backgroundColor: sessionColor }]} />
                  <Text style={[s.sessionName, { color: sessionColor }]}>{sessionName}</Text>
                  {b.isAutoGenerated && (
                    <View style={s.autoBadge}><Text style={s.autoBadgeText}>WALK-IN</Text></View>
                  )}
                  <View style={[s.statusBadge, { borderColor: `${cfg.color}44`, backgroundColor: `${cfg.color}15` }]}>
                    <Text style={[s.statusText, { color: cfg.color }]}>{cfg.emoji} {cfg.label}</Text>
                  </View>
                </View>

                {/* Gym name */}
                <Text style={s.gymName}>{gymName}</Text>

                {/* Date / Time / Ref row */}
                <View style={s.infoRow}>
                  <Text style={s.infoItem}>📅 {date}</Text>
                  <Text style={s.infoItem}>🕐 {time}</Text>
                  <Text style={[s.infoItem, { color: colors.accent, fontFamily: fonts.sansBold, letterSpacing: 1.5 }]}>#{b.bookingRef}</Text>
                </View>

                {/* Cancel button for upcoming */}
                {canCancel && (
                  <TouchableOpacity style={s.cancelBtn} onPress={() => cancelBooking(b.id)}>
                    <Text style={s.cancelBtnText}>Cancel Booking</Text>
                  </TouchableOpacity>
                )}
              </View>
            );
          })
        )}
        <View style={{ height: 30 }} />
      </ScrollView>
    </SafeAreaView>
  );
}

const s = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingVertical: 12,
  },
  back: {
    width: 38, height: 38, borderRadius: 12, backgroundColor: colors.surface,
    borderWidth: 1, borderColor: colors.border, alignItems: 'center', justifyContent: 'center',
  },
  headerTitle: { fontFamily: fonts.serif, fontSize: 20, color: '#fff' },
  filterRow: {
    flexDirection: 'row', gap: 8, paddingHorizontal: 20, marginBottom: 16,
  },
  filterBtn: {
    paddingHorizontal: 14, paddingVertical: 7, borderRadius: 20,
    backgroundColor: 'rgba(255,255,255,0.05)', borderWidth: 1, borderColor: 'rgba(255,255,255,0.08)',
  },
  filterBtnActive: { backgroundColor: colors.accentSoft, borderColor: colors.accentBorder },
  filterText: { fontFamily: fonts.sansBold, fontSize: 12, color: colors.t2 },
  filterTextActive: { color: colors.accent },
  scroll: { paddingHorizontal: 20 },
  card: {
    backgroundColor: 'rgba(255,255,255,0.04)', borderWidth: 1,
    borderRadius: radius.xl, padding: 16, marginBottom: 12,
  },
  cardTop: { flexDirection: 'row', alignItems: 'center', gap: 8, marginBottom: 8 },
  typeDot: { width: 10, height: 10, borderRadius: 5 },
  sessionName: { fontFamily: fonts.sansBold, fontSize: 13, flex: 1 },
  autoBadge: {
    backgroundColor: 'rgba(255,220,0,0.12)', borderWidth: 1, borderColor: 'rgba(255,220,0,0.3)',
    borderRadius: 10, paddingHorizontal: 6, paddingVertical: 2,
  },
  autoBadgeText: { fontFamily: fonts.sansBold, fontSize: 8, color: '#FFD700', letterSpacing: 1 },
  statusBadge: {
    borderWidth: 1, borderRadius: 12, paddingHorizontal: 8, paddingVertical: 3,
  },
  statusText: { fontFamily: fonts.sansBold, fontSize: 10, letterSpacing: 0.5 },
  gymName: { fontFamily: fonts.serif, fontSize: 17, color: '#fff', marginBottom: 10 },
  infoRow: { flexDirection: 'row', gap: 14, flexWrap: 'wrap' },
  infoItem: { fontFamily: fonts.sans, fontSize: 12, color: colors.t2 },
  cancelBtn: {
    marginTop: 12, paddingVertical: 8, borderRadius: 20, alignItems: 'center',
    backgroundColor: 'rgba(255,107,107,0.08)', borderWidth: 1, borderColor: 'rgba(255,107,107,0.2)',
  },
  cancelBtnText: { fontFamily: fonts.sansBold, fontSize: 12, color: '#FF6B6B' },
  empty: { alignItems: 'center', paddingTop: 80 },
  emptyTitle: { fontFamily: fonts.serif, fontSize: 22, color: '#fff', marginBottom: 8 },
  emptyText: { fontFamily: fonts.sans, fontSize: 14, color: colors.t2, textAlign: 'center', marginBottom: 24 },
  exploreBtn: {
    paddingHorizontal: 28, paddingVertical: 12, borderRadius: 24,
    backgroundColor: colors.accentSoft, borderWidth: 1, borderColor: colors.accentBorder,
  },
  exploreBtnText: { fontFamily: fonts.sansBold, fontSize: 14, color: colors.accent },
});
